[package]
name = "terra"
version = "0.0.1"
authors = ["Younis Shah <younisashah@gmail.com>"]

[dependencies]
ws = "0.7.3"
clap = "2.26.0"
nazar = "1.0.5"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
crossbeam = "0.3.0"